wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 30
verbose:
  desc: null
  value: 1
name:
  desc: null
  value: DenseNet169
architecture:
  desc: null
  value: DenseNet169
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697887826.75199
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 5
      10:
      - 9
      13: linux-x86_64
